### ISSUE TITLE
link后显示 Showing Recent Issues ld: framework not found JMessage

### ISSUE THREAD

**Issue by chujian** [jpush/jmessage-react-plugin#10]
已经执行link了，还是不行

**Comment by huangminlinux** [comment]
刚发布了 `jmessage-react-plugin@2.0.0-beta2` 可以更新一下插件版本，修复了部分 bug 。

Readme 上遗漏了 iOS 工程配置选项，非常抱歉。

现在更新了 Readme 可以执行如下操作。

#### iOS

- 打开工程，进入 Build Settings -> Framework search paths 添加 framework 搜索路径

  ```
  $(SRCROOT)/../node_modules/jmessage-react-plugin/ios/RCTJMessageModule
  ```

- 打开工程，进入 Build Settings -> Other Link Flag 添加一行编译选项

  ```
  -framework "JMessage"
  ```

**Comment by chujian** [comment]
恩，后来我看了里面的例子，自己重新配置好了，哈哈，谢谢，极光每次都是很及时的回复

**Comment by huangminlinux** [comment]
👌 。
