### ISSUE TITLE
sdk have not init 是什么问题？

### ISSUE THREAD

**Issue by 578939494** [jpush/jmessage-react-plugin#104]
import React, { Component } from 'react';
import { View, WebView,Platform,Dimensions,Easing,Button,Alert } from 'react-native';
import JMessage from 'jmessage-react-plugin';

type Props = {};
export default class AlignItemsBasics extends Component<Props> {
    constructor(props){
        super(props);
        JMessage.init({
          appkey: "xxx",
          isOpenMessageRoaming: false, // 是否开启消息漫游，默认不开启
          isProduction: false, // 是否为生产模式
         })
        JMessage.setDebugMode({ enable: true })
    }

    onPressLearnMore(){
         // 注册
         JMessage.register({
           username: "testetests",
           password: "testetests"
         }, () => {/*注册成功回调*/}, (error) => { console.log(error);})
    }

  render() {
    return (
      <View style={{
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems : 'flex-start'
      }}>
        <View style={{width: 50, height: 50, backgroundColor: 'powderblue'}} />
        <View style={{width: 50,height: 50, backgroundColor: 'skyblue'}} />
        <View style={{height: 100, backgroundColor: 'steelblue'}} />
        <View>
            <Button
              onPress={this.onPressLearnMore}
              title="Learn More"
              color="#841584"
              accessibilityLabel="Learn more about this purple button"
            />
        </View>
      </View>
    );

  }
};

[logall.txt](https://github.com/jpush/jmessage-react-plugin/files/2506047/logall.txt)

**Comment by JoshLipan** [comment]
按照[配置步骤](https://github.com/jpush/jmessage-react-plugin#android)检查配置，还有确认appkey是否正确

**Comment by 578939494** [comment]
@JoshLipan 配置查了好几遍了，appkey也是对的
1. android\app\src\main\AndroidManifest.xml
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.CAMERA"/>

    <meta-data android:name="JPUSH_CHANNEL" android:value="${APP_CHANNEL}" />
    <meta-data android:name="JPUSH_APPKEY" android:value="${JPUSH_APPKEY}" />

2. android\app\build.gradle
   compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        applicationId "com.tk"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0.4"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        vectorDrawables.useSupportLibrary = true
        manifestPlaceholders = [
                JPUSH_APPKEY: "f6d8f2558645986b8e15d5b9",	//在此替换你的APPKey
                APP_CHANNEL: "developer-default"		//应用渠道号
        ]
    }

3. android\app\src\main\java\com\tk\MainApplication.java
   @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    // 如果设置为 true，则不弹出 toast。
    private boolean shutdownToast = false;

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new JMessageReactPackage(shutdownToast),
            new PickerPackage(),

4. android\settings.gradle

include ':jcore-react-native'
project(':jcore-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/jcore-react-native/android')
include ':jmessage-react-plugin'
project(':jmessage-react-plugin').projectDir = new File(rootProject.projectDir, '../node_modules/jmessage-react-plugin/android')
include ':RCTWeChat'
project(':RCTWeChat').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-wechat/android')

**Comment by JoshLipan** [comment]
初始化前打开[debug模式](https://github.com/jpush/jmessage-react-plugin/blob/master/document/API.md#setdebugmode)，抓一下完整初始化的原生log提供看下

**Comment by 578939494** [comment]
最上面有 logall.txt 这个日志文件， 新建了空项目跑也跑不起来，新项目的日志 
[log.txt](https://github.com/jpush/jmessage-react-plugin/files/2509200/log.txt)

**Comment by JoshLipan** [comment]
用demo测试呢，你这个初始化好像没调用到，放在componentDidMount里呢

**Comment by JoshLipan** [comment]
官方demo呢，测试有没有问题

**Comment by 578939494** [comment]
@JoshLipan applicationId "com.sample.applicaiton" 应用ID是错的。。 message-react-plugin\example\android\app\build.gradle

**Comment by 578939494** [comment]
可以了~~
