### ISSUE TITLE
集成了JPush之后，JMessage的消息收到了，但没有进行推送

### ISSUE THREAD

**Issue by rcg1994** [jpush/jmessage-react-plugin#106]
**版本：**

"jcore-react-native": "^1.2.9",
"jmessage-react-plugin": "^2.4.4",
"jpush-react-native": "2.2.6",

**问题描述：**

iOS 端，jmessage集成后可以正常聊天。jpush集成之后，可以收到极光后台发的推送，说明推送配置都是ok的。但是IM的聊天，却没有进行推送。是不是需要进行一些设置？我记得之前用的时候，不需要做特殊处理，im消息也能推送的啊。

**Comment by rcg1994** [comment]
貌似是服务不稳定啊。。过了一天好了

**Comment by JoshLipan** [comment]
前两天服务器不稳定，已修复
