### ISSUE TITLE
最新版本的JMessage.addReceiveMessageListener 接收message为undefined!!!

### ISSUE THREAD

**Issue by JohnTree** [jpush/jmessage-react-plugin#116]

**Comment by JohnTree** [comment]
`this.receiveMessageCallBack = (message) => {
                console.warn("message"+JSON.stringify(message))
                // var msg = this.convertJMessageToAuroraMsg(message)
                // AuroraIMUIController.appendMessages([msg])
            }
            JMessage.addReceiveMessageListener(this.receiveMessageCallBack())`
com.facebook.react.bridge.NoSuchKeyException: couldn't find key roomId in dynamic object
11-23 11:48:39.784 9853-11061/com.merchant W/System.err:     at com.facebook.react.bridge.ReadableNativeMap.getString(Native Method)
11-23 11:48:39.784 9853-11061/com.merchant W/System.err:     at io.jchat.android.utils.JMessageUtils.getConversation(JMessageUtils.java:55)
11-23 11:48:39.784 9853-11061/com.merchant W/System.err:     at io.jchat.android.JMessageModule.sendMessage(JMessageModule.java:370)
11-23 11:48:39.784 9853-11061/com.merchant W/System.err:     at java.lang.reflect.Method.invoke(Native Method)

**Comment by JohnTree** [comment]
couldn't find key roomId in dynamic object这个应该不是主要问题  不知道为什么获取不了message 我是直接发送的username的消息

**Comment by JohnTree** [comment]
[InternalConversation] get userInfo failed . 打印log报这个错误

**Comment by JoshLipan** [comment]
你发送消息有配合[createSendMessage](https://github.com/jpush/jmessage-react-plugin/blob/master/document/API.md#createsendmessage)一起调用吗

**Comment by JohnTree** [comment]
有的。`JMessage.createSendMessage(message, (msg) => {
            var auroraMsg = this.convertJMessageToAuroraMsg(msg)
            if (auroraMsg.msgType === undefined) {
                return
            }

            auroraMsg.status = 'send_going'
            AuroraIMUIController.appendMessages([auroraMsg])
            AuroraIMUIController.scrollToBottom(true)
            Alert.alert('send text', JSON.stringify(msg))

            msg.messageSendingOptions = {
                isShowNotification:  true,
                isRetainOffline:  true,
                isCustomNotificationEnabled:  true,
                notificationTitle: "Title Test",
                notificationText: "context"
            };

            JMessage.sendMessage(msg, (jmessage) => {
                var auroraMsg = this.convertJMessageToAuroraMsg(jmessage)
                AuroraIMUIController.updateMessage(auroraMsg)
            }, (error) => {
            })
        })`

**Comment by JoshLipan** [comment]
> [InternalConversation] get userInfo failed . 打印log报这个错误
log 不要只提供一半，下面还有很重要的反馈信息

**Comment by JohnTree** [comment]
我就是根据demo来的。。好奇怪 居然接收不到消息 返回的message也是undefined

**Comment by JohnTree** [comment]
我刚才打印了下 JMessage.sendMessage 这个方法好像没走。。。我的写法在上面了 和demo一样的呀。。 @JoshLipan

**Comment by JohnTree** [comment]
`JMessage.createSendMessage({type: 'single', username: 'username', appKey: 'appkey', messageType: 'text / image / voice / file / location / custom',text:'message text'}, (message) => {
  JMessage.sendMessage({id: message.id, type: 'single', username: 'username',appKey: 'appKey',}, () => {
    // 成功回调
  }, () => {
    // 失败回调
  })
})`

你的demo应该有问题 我这么写 就能发送 按照chat.js里面JMessage.sendMessage这个方法走不通。 @JoshLipan

**Comment by JohnTree** [comment]
果然是这样 demo里的JMessage.sendMessage里的传参格式有错误 我改了之后好了
