### ISSUE TITLE
processApplyJoinGroup 这个能用吗？

### ISSUE THREAD

**Issue by 578939494** [jpush/jmessage-react-plugin#125]
我用addReceiveApplyJoinGroupApprovalListener监听到的事件id
Object { eventId: "308289253", groupId: "28657359", isInitiativeApply: true, reason: "申请入群"}
然后用processApplyJoinGroup 处理批量处理入群（公开群）申请 提示找不到事件
Object { description: "Parameters error: can't get event through 308289253", code: 1 }
是什么情况？
@JoshLipan

**Comment by JoshLipan** [comment]
[社区讨论](https://community.jiguang.cn/t/topic/30975)
