### ISSUE TITLE
setBadge现在 iOS Only了嘛？

### ISSUE THREAD

**Issue by JohnTree** [jpush/jmessage-react-plugin#126]
/**
     * iOS Only
     * 设置服务器 badge 值，用于 badge+1 功能
     * 成功返回 true
     */
    static setBadge (badge, cb) {
        if (Platform.OS === 'ios') {
            JMessageModule.setBadge(badge, value => {
              cb(value)
            })
        }
    }

**Comment by huangminlinux** [comment]
是的。
