### ISSUE TITLE
react-redux配合navigation该怎么弄啊?

### ISSUE THREAD

**Issue by yt7649757** [jpush/jmessage-react-plugin#13]
我看网上用的都是navigator加redux的案例
比如
<Provider store={store}>
        <App />
      </Provider>
provider里面包裹的是一个navigator组件，如果是navigation这里该怎么写啊，
const MyApp = StackNavigator({
    Login: {
        screen: Login,
        navigationOptions: {
            header: null
        }
    },
    Main: {
        screen: Main,
        navigationOptions: {
            header: null
        }
    }
});
navigation路由文件一般是这些写法，，不是一个组件，，该怎么在provider中引用啊

**Comment by huangminlinux** [comment]
这个问题和本库无关，建议到相关地方提问
