### ISSUE TITLE
可以提供 SDK ErrorCode 定义列表吗

### ISSUE THREAD

**Issue by DMCHZP** [jpush/jmessage-react-plugin#135]
插件返回 ErrorCode 定义 和 原生 IOS Android ErrorCode 不一致。

**Comment by JoshLipan** [comment]
都是直接拿返回的原生的 ErrorCode 和 ErrorMessage，[iOS](https://docs.jiguang.cn/jmessage/client/im_errorcode_ios/) 和 [Android](https://docs.jiguang.cn/jmessage/client/im_errorcode_android/) 原生就是不一样的
