### ISSUE TITLE
getHistoryMessages方法IOS不能获取unreceiptCount

### ISSUE THREAD

**Issue by 1512751361** [jpush/jmessage-react-plugin#155]
![G$HRDP3~OTW(XS%}Z)PWXN7](https://user-images.githubusercontent.com/24776858/55767735-b17aca80-5aac-11e9-9237-2ac3184a5b24.png)
使用getHistoryMessages方法获取到的历史消息，IOS的消息内容里没有unreceiptCount已读回执的人数字段，android的有？？？？
jmessage-react-plugin：^3.1.3

**Comment by wicked-tc130** [comment]
3.1.5已加
