### ISSUE TITLE
Something Error : JMessage init()

### ISSUE THREAD

**Issue by maxlxq** [jpush/jmessage-react-plugin#19]
`TypeError:Cannot read property 'setup' of undefined
This error is loacted at:
   in App (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:126)
    in AppContainer (at renderApplication.js:34)`

`let params = {
          'appkey': "***",
          'isOpenMessageRoaming': false,
          'isProduction': false,
          'channel': ""
      };
      JMessage.init(params);
      JMessage.getMyInfo((myInfo) => {
        console.log('myInfo:',myInfo);
      })`

**Comment by maxlxq** [comment]
修改源码中注册的那个地方，仔细看就知道了

**Comment by chaihb** [comment]
@maxlxq hi, ios遇到了同样的问题，修改哪里，可以说明白些吗？谢谢
