### ISSUE TITLE
RN-android开发，项目一直new JMessageReactPackage(false)一直报错起不来。哪位仁兄能看下哪里错了

### ISSUE THREAD

**Issue by wolfkindom** [jpush/jmessage-react-plugin#208]
按照文档要求	\android\app\src\main\AndroidManifest.xml     \android\app\build.gradle     \android\settings.gradle分别加入极光配置，并新建react-native.config.js加入安卓配置代码，还是报new实例对象的错，不知哪里出了问题？
![66](https://user-images.githubusercontent.com/49385294/118525226-85dd6a80-b771-11eb-8daa-667d5ec1a70f.png)
![67](https://user-images.githubusercontent.com/49385294/118525233-870e9780-b771-11eb-97a1-bf2b36b499ec.png)
![68](https://user-images.githubusercontent.com/49385294/118525235-87a72e00-b771-11eb-94f4-7d74f1183325.png)
![70](https://user-images.githubusercontent.com/49385294/118525237-883fc480-b771-11eb-8da4-f08a5a22cd4d.png)
![88](https://user-images.githubusercontent.com/49385294/118525240-88d85b00-b771-11eb-852f-fdc1ec6a32cd.png)

**Comment by chenshaxuanjing** [comment]
请问最后解决了嘛
