### ISSUE TITLE
jmessage-react-plugin出错

### ISSUE THREAD

**Issue by UchihaKutter** [jpush/jmessage-react-plugin#23]
jmessage-react-plugin-v2.1.0；
jcore-react-native-v1.2.1；
Android端出现错误：
Could not invoke JMessageModule.setDebugMode

null

cn.jpush.im.android.api.JMessageClient
invoke
    JavaMethodWrapper.java:374
invoke
    JavaModuleWrapper.java:162
run
    NativeRunnable.java
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:135
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:818

**Comment by KenChoi1992** [comment]
@UchihaKutter 有没有传入正确的参数？
