### ISSUE TITLE
JMessage.exitConversation

### ISSUE THREAD

**Issue by a852882874** [jpush/jmessage-react-plugin#24]
JMessage.exitConversation，页面销毁之后，没反应，，咋回事

**Comment by KenChoi1992** [comment]
@a852882874 这个方法本来就没有回调。

**Comment by a852882874** [comment]
@KenChoi1992 但是退出之后，收到消息，也不会震动，没有声音。。重新登录退出应用才可以，，就是一旦执行了enterConversation进入会话，，当页面销毁之后，收到消息就不提示了

**Comment by KenChoi1992** [comment]
@a852882874 enterConversation 在 Native 需要拿到 Activity，估计这个没拿到，变成了 Application Context，这样一来无论在哪个页面都是同一个会话。因为 RN 本身只用了一个 MainActivity。除非你跳转到聊天界面是另一个 Activity（界面还是用 RN 写），这样技术上来讲应该就没问题了。
