### ISSUE TITLE
发送好友申请消息， 接收方收不到消息

### ISSUE THREAD

**Issue by UchihaKutter** [jpush/jmessage-react-plugin#26]
JMessage.addContactNotifyListener 监听不到消息

**Comment by huangminlinux** [comment]
那个平台的，iOS 还是 android?

**Comment by UchihaKutter** [comment]
android

**Comment by UchihaKutter** [comment]
我没有集成Jpush

**Comment by UchihaKutter** [comment]
没有集成jpush应该没关系

**Comment by KenChoi1992** [comment]
@UchihaKutter Android 这边还没加上，还有几个新接口加上，然后下午发布新版本。

**Comment by UchihaKutter** [comment]
这样子啊，发布好了告诉我一声

**Comment by UchihaKutter** [comment]
发布好了吗

**Comment by UchihaKutter** [comment]
addReceiveMessageListener也监听不到

**Comment by UchihaKutter** [comment]
@KenChoi1992  没有LOG 打印：“ContactNotifyEvent”

**Comment by UchihaKutter** [comment]
@KenChoi1992 jmessage 的监听事件都无法监听到， jmessage-react-pluin2.1.0， jcore-react-pluin1.2.1

**Comment by KenChoi1992** [comment]
@UchihaKutter 有没有调用 init 方法
