### ISSUE TITLE
JMessage.sendMessage方法错误

### ISSUE THREAD

**Issue by sofwu** [jpush/jmessage-react-plugin#34]
Error Domain=jmsg_error Code=865003 "target is 0" UserInfo={NSLocalizedDescription=target is 0}

**Comment by KenChoi1992** [comment]
@sofwu 发送的 target 是空的吧？

**Comment by sofwu** [comment]
我是发给管理员账号的

**Comment by zhjh5337** [comment]
Message message = conversation.getMessage(map.getInt(Constant.ID));
改为
Message message = conversation.getMessage(Integer.parseInt(map.getString(Constant.ID)));

**Comment by KenChoi1992** [comment]
2.1.4 版本已修复
