### ISSUE TITLE
接收到的视频消息无法使用

### ISSUE THREAD

**Issue by nextdooroldwang** [jpush/jmessage-react-plugin#44]
请问下JMessage监听接收到视频消息怎么显示出来？好像没有可用的字段。
![2hu c6np ss q5o ol6ec4](https://user-images.githubusercontent.com/18671240/37691485-61d28024-2ced-11e8-9e62-9f39c8495960.png)

其他消息类型接收到的消息都是正常可用的数据。

"jmessage-react-plugin": "^2.2.4",
"react-native": "0.53.0",

**Comment by huangminlinux** [comment]
看你收到的消息是自定义消息不是文件消息。

**Comment by nextdooroldwang** [comment]
@huangminlinux 
![image](https://user-images.githubusercontent.com/18671240/37691784-2e844c6e-2cef-11e8-9983-af9d87367762.png)

**Comment by huangminlinux** [comment]
什么情况出现这种问题？ 
iOS 发送给 android 还是 android 发送给 iOS？
iOS 发送文件消息给 iOS 是否正常？
Android 发送文件消息给 Android 是否正常？

**Comment by nextdooroldwang** [comment]
@huangminlinux 
Android 发送视频文件消息给 Android 出现这种问题。
文字，图片，语音，都正常，只有发视频的时候会出现这个问题

**Comment by KenChoi1992** [comment]
@nextdooroldwang 你的 message type 应该使用 file。然后通过 fileName 得到路径。

**Comment by nextdooroldwang** [comment]
@KenChoi1992 我按照file的messageType发送消息

```
JMessage.createSendMessage({ type: 'single', username: 'qq123321', messageType: 'file', path: mess.mediaPath },
            (message) => {
                JMessage.sendFileMessage({ type: 'single', username: 'qq123321', path: mess.mediaPath }, (msg) => {
```

会报参数错误，发送消息失败。

code:1
description:"Parameters error"

path:'/storage/emulated/0/DCIM/Camera/VID_20180321_133717.mp4'
你看我写的有啥问题不？跟文档对了很多次，，没看出来问题在哪

**Comment by nextdooroldwang** [comment]
解决了，在参数里加了一个fileName: ''  就可以了。麻烦官方文档更新一下啊。要不这个坑。。。
