### ISSUE TITLE
使用downloadFile报Wrong message type错

### ISSUE THREAD

**Issue by nextdooroldwang** [jpush/jmessage-react-plugin#45]
这是我收到的文件：

![](https://community.jiguang.cn/uploads/default/original/3X/0/8/08a156a531de65c108134b9b75c67235b34fe917.png)

这是使用downloadFile下载的配置

![](https://community.jiguang.cn/uploads/default/original/3X/1/1/1126612acaab8d99cd32b45fa8f693ee9c4be5ea.png)

这是报错

![](https://community.jiguang.cn/uploads/default/original/3X/f/5/f55d9e4bf4f82cea140867488caa5f76026c7a16.png)

Android
"jmessage-react-plugin": "^2.3.1",
"react-native": "0.53.0",

**Comment by KenChoi1992** [comment]
新版本修复了。
