### ISSUE TITLE
JMSGPushError:request timeout

### ISSUE THREAD

**Issue by wangfaguo** [jpush/jmessage-react-plugin#48]
{ description: 'Error Domain=jmsg_error Code=6002 "JMSGPushError:request timeout" UserInfo={NSLocalizedDescription=JMSGPushError:request timeout}',

iPhone真机调用jmessage的登录方法请求超时，用模拟器就没问题，为啥？

**Comment by huangminlinux** [comment]
切换为同一个网络环境看还有没问题
