### ISSUE TITLE
运行example报错

### ISSUE THREAD

**Issue by 25juan** [jpush/jmessage-react-plugin#51]
启动运行example报错
`Activity class {com.sample.application/com.sample.application.MainActivity} does not exist.`
![image](https://user-images.githubusercontent.com/14308183/39103277-6df61db2-46dc-11e8-93cc-b15f800cc4a1.png)

**Comment by JoshLipan** [comment]
打开/android/app/build.gradle文件，注释掉defaultConfig下的applicationId试试

**Comment by JoshLipan** [comment]
直接导入AS运行也是可以的

**Comment by 25juan** [comment]
那你们可以把这个问题修改提交了 @JoshLipan
