### ISSUE TITLE
RCTJMessageModule.m：downloadVoiceFile 1659行 错误

### ISSUE THREAD

**Issue by pjjch** [jpush/jmessage-react-plugin#55]
1659行：
        failCallback(@[@{@"messageId": message.msgId,
                         @"filePath": [mediaContent originMediaLocalPath]}]);
应改为：
        successCallback(@[@{@"messageId": message.msgId,
                         @"filePath": [mediaContent originMediaLocalPath]}]);

**Comment by huangminlinux** [comment]
👌下个版本一起修复这个问题。
