### ISSUE TITLE
关于上传头像问题

### ISSUE THREAD

**Issue by 25juan** [jpush/jmessage-react-plugin#57]
为什么我修改了当前的头像没有保存到 jmessage 的服务器，而是保存在本地，那如果我后面换一个手机登录，是不是我在之前手机上更新的头像没有了。附上保存之后的头像路径：
```
/data/user/0/com.lgzq/files/images/small-avatar/B1A07E096487FA0E24A4285FE2873D9C
```

**Comment by JoshLipan** [comment]
修改头像会保存到服务器，这和返回的头像路径是本地路径没有冲突；
更换设备登录时会自动下载头像保存，获取头像路径也是本地路径。

**Comment by 25juan** [comment]
但是下载出来的这个头像文件没有后缀名，用不了呢

**Comment by huangminlinux** [comment]
通过 react-native-fs 读取图片数据，使用数据显示就行，demo 应该有。 可以参考 https://github.com/jpush/jmessage-react-plugin/blob/master/example/app/routes/Home/MyInfo/index.js#L79

**Comment by 25juan** [comment]
谢谢
