### ISSUE TITLE
Could not invoke JMessageModule.setup  null 集成出现的问题

### ISSUE THREAD

**Issue by bighaohao** [jpush/jmessage-react-plugin#59]
// js  
"jcore-react-native": "^1.2.6",
    "jmessage-react-plugin": "^2.3.6",
    "react": "16.2.0",
    "react-native": "0.52.2",

// android
compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.xxxxxxxx"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 2
        versionName "2.2"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
        manifestPlaceholders = [
                JPUSH_APPKEY: "",	//在此替换你的APPKey
                APP_CHANNEL: "developer-default"		//应用渠道号
        ]
    }

**Comment by xbgph** [comment]
@huangminlinux 谢谢了，是link的问题
