### ISSUE TITLE
发送视频不显示，没有path这个字段

### ISSUE THREAD

**Issue by hg542006810** [jpush/jmessage-react-plugin#63]
![image](https://user-images.githubusercontent.com/16329156/42012947-738bb41a-7acd-11e8-88d2-809d21f94126.png)

语音，图片，都可以，唯独视频不可以

![image](https://user-images.githubusercontent.com/16329156/42012953-7abffcc8-7acd-11e8-9cde-e5f3354e1703.png)

这是代码 
![image](https://user-images.githubusercontent.com/16329156/42013000-aac0887a-7acd-11e8-8887-73f199f633e0.png)

**Comment by JoshLipan** [comment]
哪个版本，看下这个issue #44

**Comment by hg542006810** [comment]
看了 
"jcore-react-native": "^1.2.6"
"jmessage-react-plugin": "^2.3.6"
"react-native": "0.55.3"
就是照着他这样做的 但还是没解决

**Comment by hg542006810** [comment]
没有 我不需要进行下载 应该是点击的时候进行下载。sendFileMessage返回给我的就没有path 但是实际上是能获取到path的 
![image](https://user-images.githubusercontent.com/16329156/42017066-5cbcfe20-7ae0-11e8-8120-da8d14199570.png)
下面是代码
![image](https://user-images.githubusercontent.com/16329156/42017084-686c1c42-7ae0-11e8-80f3-b6ee498f564e.png)

**Comment by JoshLipan** [comment]
实际上又能获取到path是什么意思，请用A代表发送方，B代表接收方，具体哪个API有问题，重新描述一下你的问题

**Comment by hg542006810** [comment]
A发送视频到B处，A和B处都不会显示出视频。
通过getHistoryMessages接口可以看到返回的数据，无论是语音，拍照，相册，都会有path这个属性

这是语音文件(getHistoryMessages接口)
![image](https://user-images.githubusercontent.com/16329156/42017650-66489920-7ae2-11e8-9d11-02807e0562ec.png)

唯独发送的视频 没有path这个属性，这也是导致视频显示不出来的根本原因。

这是视频文件(getHistoryMessages接口)
![image](https://user-images.githubusercontent.com/16329156/42017686-7efdf064-7ae2-11e8-8aa6-56f1e5a8cf78.png)

至于为什么没有path，我做了很多调试。最开始调用了 createSendMessage 接口 
传入参数为：path，messageType("file"),type("single"),username

type为file的时候createSendMessage接口返回的参数并没有path
但是type为其他的时候(除了text)，createSendMessage接口返回的参数都包含了path。
我想知道type为file的时候为什么不会返回path

**Comment by JoshLipan** [comment]
createSendMessage type为file 会返回fileName，不会返回path

**Comment by JoshLipan** [comment]
dev分支已添加file 类型返回path，下个版本发布同步上来，这个先关闭了
