### ISSUE TITLE
getHistoryMessage 和 onReceiveMessage问题

### ISSUE THREAD

**Issue by sunkaigoon** [jpush/jmessage-react-plugin#67]
"react": "^16.4.0",
"react-native": "^0.55.4",
"jmessage-react-plugin": "^2.3.7",
"aurora-imui-react-native": "^0.10.8"

前提：使用createJMessage创建消息，sendJMessage发送消息
问题1：当发送视频文件(type: 'file')，发送过程没有问题，但接收的时候message里fileName: null, path: null
问题2：A用a手机给B的b手机发送了消息，包括文字、视频、音频、图片，视频问题如问题1。当A，B互换手机登录自己的账号（isOpenMessageRoaming: true），这时用getHistoryMessage获取的历史消息中，视频、图片的path为空或没有path字段，音频有时也会这样。文字消息没有问题。

**Comment by huangminlinux** [comment]
https://github.com/jpush/jmessage-react-plugin/blob/master/document/API.md#downloadfile 这个方法调用了没？

**Comment by sunkaigoon** [comment]
也就是说，图片，音频文件在漫游的情况下要手动下载，包括图片的缩略图。视频文件在任何情况下都要手动下载？

**Comment by huangminlinux** [comment]
一般判断就是资源文件为空，就需要调用相应的下载方法。

**Comment by sunkaigoon** [comment]
这种情况，图片的缩略图就需要我自己来做了，是这么个情况吧

**Comment by huangminlinux** [comment]
下载图片的缩略图也有相应的方法。

**Comment by sunkaigoon** [comment]
downloadOriginalImage 只看到了这个方法😶

**Comment by huangminlinux** [comment]
确实还没加上这个方法，下个版本添加这个 API。

**Comment by sunkaigoon** [comment]
好的，感谢，待会我自己把这个issues关了
