### ISSUE TITLE
系统消息对象返回js为[null]

### ISSUE THREAD

**Issue by dogbutcat** [jpush/jmessage-react-plugin#71]
## Environment
package: jmessage-react-plugin@2.3.9
platform: android

## Description
在控制台新建群组并添加成员后，调用拉取历史消息API**JMessage.getHistoryMessages**时，返回数据体Message为[null]，实际上应是eventType为group_member_added的object，查看源码发现在如下case中
https://github.com/jpush/jmessage-react-plugin/blob/c7e9843008d6dc4662afd4255e45d402b6327d67/android/src/io/jchat/android/utils/ResultUtils.java#L201-L224
执行之后并没有break，结果直接跳转default并且返回了null而非result，导致js获取数据为[null]出错。不知是否为bug

## Expectation
系统消息正常返回

**Comment by dogbutcat** [comment]
#72

**Comment by JoshLipan** [comment]
Thank you for your PR and help us a lot.
