### ISSUE TITLE
downloadThumbGroupAvatar调用这个API, 群头像为空,会crash

### ISSUE THREAD

**Issue by Yao916952836** [jpush/jmessage-react-plugin#73]
callback回来, 没做非空处理

successCallback(@[@{@"id": objectId, @"filePath": group.thumbAvatarLocalPath

**Comment by huangminlinux** [comment]
下个版本处理这个问题

**Comment by huangminlinux** [comment]
可以升级到 + jmessage-react-plugin@2.4.0
