### ISSUE TITLE
 不知道是不是版本的问题，安卓配置总是报错

### ISSUE THREAD

**Issue by quietautumn** [jpush/jmessage-react-plugin#74]
这是现在所用的rn的版本：
![80a5de06-ca3d-43f4-b31a-bd8079ead997](https://user-images.githubusercontent.com/16301518/44186431-f6cc3f80-a14b-11e8-8a3c-978db695a4cd.png)
这是报错信息：
![74f00088-5da8-4f4f-b74a-339495325e50](https://user-images.githubusercontent.com/16301518/44186462-224f2a00-a14c-11e8-8d34-530e15e62eac.png)
查了很多文档，但是都没发现有解决的方案，有没有哪位大神能解答一下？

**Comment by JoshLipan** [comment]
看下是不是gradle版本问题：
/android/build.gradle修改如下：
```
dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```

/android/gradle/wrapper/gradle-wrapper.properties中修改：
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
```

**Comment by quietautumn** [comment]
非常感谢，现在能跑起来了，但是还有其他问题，参考一下example不成功再来继续提issue，谢谢
