### ISSUE TITLE
获取会话之后获取用户头像问题

### ISSUE THREAD

**Issue by 25juan** [jpush/jmessage-react-plugin#83]
环境：
"react-native": "^0.53.3",
"jmessage-react-plugin": "^2.4.0",
在进入APP ，我获取当前会话列表并展示出来，然后通过`react-native-fs`来读取图片路径并且转换成为bse64 编码并且展示出来，结果出现下面的头像找不到的问题。但是只要给对方发送一条消息之后即可正常显示。

![image](https://user-images.githubusercontent.com/14308183/44404351-45813b80-a589-11e8-838e-3aeee5fe7518.png)

**Comment by JoshLipan** [comment]
你可以在调用显示前先调用[下载头像](https://github.com/jpush/jmessage-react-plugin/blob/master/document/API.md#downloadthumbuseravatar)，成功返回后再展示

**Comment by 25juan** [comment]
好的，谢谢，我看看
