### ISSUE TITLE
downloadVoiceFile返回错误的参数

### ISSUE THREAD

**Issue by dogbutcat** [jpush/jmessage-react-plugin#85]
### Description
下载音频中判断消息类型的时候错误，判断目标消息类型为image，但实际应该为voice导致无法下载。。。
https://github.com/jpush/jmessage-react-plugin/blob/8946f31f8c377abecfbe235ca20e853a5451df0b/android/src/io/jchat/android/JMessageModule.java#L1115-L1132

**Comment by JoshLipan** [comment]
v2.4.2已修复，谢谢建议，对我们帮助很大

**Comment by dogbutcat** [comment]
@JoshLipan 也感谢你们提供了免费的通信服务以及RN版的支持
