### ISSUE TITLE
RN iOS收不到消息推送

### ISSUE THREAD

**Issue by SunRainMi** [jpush/jmessage-react-plugin#88]
iOS收不到推送消息,但能正常聊天!请问一下需要怎么处理?

**Comment by huangminlinux** [comment]
有没有成功集成 jpush-react-native 这个插件？

**Comment by SunRainMi** [comment]
@huangminlinux 需要配合jpush,才能收到实时推送吗

**Comment by huangminlinux** [comment]
是的，安装 jpush-react-native 要保证 appKey 一致。

**Comment by SunRainMi** [comment]
@huangminlinux 那为什么Android的不用集成jpush都可以用呢?

**Comment by huangminlinux** [comment]
理论上也可以，不过 iOS 需要改原生代码， jpush-react-native 这个插件自动化了这些步骤，所以使用  jpush-react-native 这个插件更简单。

**Comment by SunRainMi** [comment]
@huangminlinux 知道了,谢谢
