### ISSUE TITLE
怎么实时获取会话列表的消息

### ISSUE THREAD

**Issue by quietautumn** [jpush/jmessage-react-plugin#90]
当进入会话列表，并且停留在会话列表的时候，有新消息发送过来之后怎么刷新会话列表的消息呢

**Comment by dogbutcat** [comment]
我是通过添加消息监听，通过监听回调更新

API文档 [addReceiveMessageListener](https://github.com/jpush/jmessage-react-plugin/blob/master/document/API.md#addreceivemessagelistener)

**Comment by quietautumn** [comment]
@dogbutcat ,谢谢，这个能实现需求
