### ISSUE TITLE
安卓退出后台，点击推送的消息进入app之后，无法获取消息内容

### ISSUE THREAD

**Issue by quietautumn** [jpush/jmessage-react-plugin#92]
安卓能直接推送，我也集成了jpush的插件，但是现在希望启动app后能跳转到会话的页面，但是jmessage推送的消息在启动页面之后无法获取到推送的消息内容，只能留在首页，直接在极光的官网推送的消息是可以获取消息内容的，请问实现这个功能有相关的文档吗？

**Comment by dogbutcat** [comment]
你指的推送内容是跳转conversation时需要的相关参数还是消息内容？

单纯的消息内容的话Android在这个监听中能正常获取到的: [addClickMessageNotificationListener](https://github.com/jpush/jmessage-react-plugin/blob/master/document/API.md#addclickmessagenotificationlistener)

**Comment by quietautumn** [comment]
好的，我试试，我还以为安卓的也是用安卓的监听事件获取的
