### ISSUE TITLE
Android  获取用户头像,返回本地地址 但不能读取

### ISSUE THREAD

**Issue by wennjie** [jpush/jmessage-react-plugin#94]
返回地址 如下 
![image](https://user-images.githubusercontent.com/22758379/45068842-019b4400-b0fc-11e8-9e60-4265f07212ae.png)

本地未找到该文件夹，及文件。  

APP 文件存储 权限已开启

**Comment by JoshLipan** [comment]
参考下#83

**Comment by wennjie** [comment]
@JoshLipan  未解决。 原因是 返回地址未写入到 存储。 
fs 获取该地址 找不到该文件。

**Comment by wennjie** [comment]
"jcore-react-native": "^1.2.9",
"jmessage-react-plugin": "^2.4.2",
"jpush-react-native": "^2.2.9",
 "react-native-fs": "^2.11.15",

**Comment by JoshLipan** [comment]
init后调用[setDebugMode](https://github.com/jpush/jmessage-react-plugin/blob/master/example/android/app/src/main/java/com/sample/application/MainApplication.java#L54)为true,然后抓取下从初始化开始到下载头像失败原生log
抓取方式：adb logcat -v time ->a.log
同时提供你的传参和原生log

**Comment by wennjie** [comment]
[wenjie_app_a.log](https://github.com/jpush/jmessage-react-plugin/files/2355516/wenjie_app_a.log)
获取用户信息
getUserInfo(username,callback){
            JMessage.getUserInfo({ username },
                (userInfo) => {
                    console.log(userInfo)
                    if(!userInfo.avatarThumbPath){
                        this.downloadOriginalUserAvatar(username,(ret)=>{
                            console.log(ret)
                            userInfo.avatarThumbPath = ret.filePath
                            callback(userInfo)
                        })
                    }
                    callback(userInfo)
                }, (err) => {
                    Code(err)
                })
    }

获取个人信息
getInfo(navigation){
        this.navigation=navigation
        JMessage.getMyInfo((myInfo) => {
            
            if (myInfo.username) {
                AsyncStorage.setItem('USER',JSON.stringify(myInfo))
                this.navigation.dispatch({type:'USER',user:myInfo})
                this.navigation.navigate({ routeName:"StackNavigator" })
                this.addListener()
                this.getFriends()
            } else {
                this.navigation.navigate({ routeName:"Login" })
            }
        })
    }

**Comment by wennjie** [comment]
@JoshLipan

**Comment by wennjie** [comment]
@JoshLipan   手机上无该目录

**Comment by wennjie** [comment]
@JoshLipan  是否因为权限问题 导致未写入？ 
AndroidManifest.xml
 <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
 <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
已添加 读取和写入权限

**Comment by wennjie** [comment]
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Comment by wennjie** [comment]
·<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />·

**Comment by wennjie** [comment]
![image](https://user-images.githubusercontent.com/22758379/45197417-a9974580-b293-11e8-95f8-d6fc4d0214aa.png)

**Comment by JoshLipan** [comment]
我这边测试没问题，是不是你显示传参的问题，参考[demo](https://github.com/jpush/jmessage-react-plugin/blob/4dbf9dc68954dc5216cb32cb26c86e6526ee4398/example/app/routes/Home/MyInfo/index.js#L98)显示本地图片路径

**Comment by UchihaKutter** [comment]
为什么不返回完整图片路径
