### ISSUE TITLE
ios 监听好有事件闪退

### ISSUE THREAD

**Issue by wennjie** [jpush/jmessage-react-plugin#95]
ios 监听好有事件闪退

JMessage.addContactNotifyListener(listener)  监听好友事件。
被删除 触发 contact_deleted ，时闪退
xcode 暂定

**Comment by wennjie** [comment]
ios log
------------------
2018-09-06 20:54:04.913976+0800 huiliaoJmessage[16064:403909] Task <08935CFD-E74C-4712-9620-7E372292963D>.<2> finished with error - code: -1001
2018-09-06 20:54:05.585645+0800 huiliaoJmessage[16064:403794] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000101e531e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x0000000105f4a031 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000101e930bc _CFThrowFormattedException + 194
	3   CoreFoundation                      0x0000000101d66951 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x0000000101d667db +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   huiliaoJmessage                     0x0000000100623a33 -[JMessageHelper onReceiveFriendNotificationEvent:] + 2339
	6   CoreFoundation                      0x0000000101dd6ccc __invoking___ + 140
	7   CoreFoundation                      0x0000000101dd6b84 -[NSInvocation invoke] + 308
	8   CoreFoundation                      0x0000000101def8d6 -[NSInvocation invokeWithTarget:] + 54
	9   libdispatch.dylib                   0x00000001090a27ab _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x00000001090a37ec _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x00000001090ae8cf _dispatch_main_queue_callback_4CF + 628
	12  CoreFoundation                      0x0000000101e15c99 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	13  CoreFoundation                      0x0000000101dd9ea6 __CFRunLoopRun + 2342
	14  CoreFoundation                      0x0000000101dd930b CFRunLoopRunSpecific + 635
	15  GraphicsServices                    0x000000010bf93a73 GSEventRunModal + 62
	16  UIKit                               0x00000001029b9057 UIApplicationMain + 159
	17  huiliaoJmessage                     0x00000001000b263f main + 111
	18  libdyld.dylib                       0x0000000109120955 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by huangminlinux** [comment]
可以升级到 2.4.4版本
```
npm i jmessage-react-plugin@2.4.4
```
