### ISSUE TITLE
发送图片一直提示参数错误

### ISSUE THREAD

**Issue by quietautumn** [jpush/jmessage-react-plugin#96]
昨天能正常发送图片，今天过来没有修改代码，一直提示参数错误，而且昨天发送成功的图片也不能显示了，下面是提交的参数：
![906c9259-2686-47b6-97cf-ded944462306](https://user-images.githubusercontent.com/16301518/45195685-63d67f00-b28b-11e8-9a47-d0270ab8fc4e.png)

**Comment by JoshLipan** [comment]
使用的插件版本，还有提供下你的传参

**Comment by quietautumn** [comment]
刚刚看了一下#25，要把前面的file://去掉，昨天应该是用的ios调试的
