### ISSUE TITLE
Android 头像上传问题 

### ISSUE THREAD

**Issue by wennjie** [jpush/jmessage-react-plugin#97]
安卓8.0 获取获取相册照片地址 "file:///storage/emulated/0/Pictures/1cfe65aa-b85a-409f-953d-73f740fe19e4-compressed.jpg"

导致 上传时 Java new File（）及判断
` String path = map.getString("imgPath");
            File file = new File(path);
            Log.i("WENJIEMESSAGE", "file->"+file+" file.exists()->"+file.exists()+" file.isFile()->"+file.isFile());
            if (file.exists() && file.isFile()) {
                JMessageClient.updateUserAvatar(file, new BasicCallback() {
                    @Override
                    public void gotResult(int status, String desc) {
                        mJMessageUtils.handleCallback(status, desc, success, fail);
                    }
                });
            }`

file->file:/storage/emulated/0/Pictures/5d995ce1-6844-4645-a24a-25b6f185b066-compressed.jpg 
file.exists()->false
file.isFile()->false

**Comment by wennjie** [comment]
导致文件上传失败

**Comment by JoshLipan** [comment]
传“storage/emulated/0/Pictures/1cfe65aa-b85a-409f-953d-73f740fe19e4-compressed.jpg”试试
