### ISSUE TITLE
聊天室功能， 安卓进入聊天室后，可以发送消息，但是收不到消息

### ISSUE THREAD

**Issue by forrest23** [jpush/jmessage-react-plugin#98]
"jcore-react-native": "^1.2.9",
    "jmessage-react-plugin": "^2.4.4",
    "jpush-react-native": "^2.2.9",
    "react": "^16.0.0-alpha.6",
    "react-native": "^0.44.0",

进入聊天室后，安卓上发送的消息，苹果可以收到，但是安卓上却收不到消息，无论是安卓还是苹果发的消息？是安卓哪里权限的问题嘛？还是别的什么问题？

**Comment by forrest23** [comment]
用的是 addReceiveChatRoomMsgListener 这个监听

**Comment by JoshLipan** [comment]
将插件对应位置[RECEIVE_MSG_EVENT](https://github.com/jpush/jmessage-react-plugin/blob/master/android/src/io/jchat/android/JMessageModule.java#L2063)改成RECEIVE_CHAT_ROOM_MSG_EVENT试下

**Comment by forrest23** [comment]
应该就是这个事件名称写错了造成的！我加了 addReceiveMessageListener 监听，安卓上就能收到聊天室的信息了。 @JoshLipan 我去改下你说的 再试下

**Comment by forrest23** [comment]
@JoshLipan 按你说的改了就可以了 希望下个版本能改下这个Bug

**Comment by JoshLipan** [comment]
下个版本修复，谢谢你的issue，对我们帮助很大
