### ISSUE TITLE
进入聊天室，会莫名收到昨天发的一条消息

### ISSUE THREAD

**Issue by forrest23** [jpush/jmessage-react-plugin#99]
进入聊天室，会莫名收到昨天发的一条消息

![image](https://user-images.githubusercontent.com/6458126/45536712-de2b7400-b834-11e8-8c0d-99d2e5b5a60b.png)

如上图所示，这是昨天发的一条消息，为什么今天进入聊天室会收到这样的消息，而且每次进入都会有

**Comment by JoshLipan** [comment]
你是进入昨天的聊天室吗，每次进入聊天室会拉取最近的消息。

**Comment by forrest23** [comment]
> 你是进入昨天的聊天室吗，每次进入聊天室会拉取最近的消息。

我一直进的是同一个聊天室，但每次进去就会显示一条消息，而且也不是最近的消息！不是说聊天室不会保存消息的嘛？

**Comment by JoshLipan** [comment]
设置[setDebugMode](https://github.com/jpush/jmessage-react-plugin/blob/master/document/API.md#setdebugmode)为true，抓个原生log看看

**Comment by forrest23** [comment]
每次进入聊天室，会默认拉取最近的50条消息，是一个数组列表，是我之前没处理好。
